### ISSUE TITLE
death listener registration error

### ISSUE THREAD

**Issue by emarteca** [indutny/tlsnappy#5]
Hi all, I've been working on a tool to identify instances of events registered to the wrong object in uses of some JavaScript event-driven APIs, as part of a research project.
The tool flagged [line 49](https://github.com/indutny/tlsnappy/blob/master/example/server.js#L49) in example/server.js, on the registration of the listener for `death`.

The reason I believe this is an error is as follows (from looking at the [nodejs cluster API documentation](https://nodejs.org/api/cluster.html#cluster_class_worker)):
the listener for `death` is registered on the return from [the call to `cluster.fork()`](https://nodejs.org/api/cluster.html#cluster_cluster_fork_env).
However, `death` is not an event on cluster.Worker.

Thanks!

**Comment by indutny** [comment]
Hey!

This is a very very old module and it uses outdated event names. I don't think that anyone uses it nor that it compiles for the recent Node.js versions.

Thank you for reaching out and good luck with your research!

**Comment by emarteca** [comment]
Hey, thanks for the speedy response, and for letting me know!
